base_url: "https://www.automationexercise.com/"
api_base_url: "https://automationexercise.com/api"
browser: "chromium"
headless: true
viewport:
  width: 1280
  height: 720
db:
  host: "localhost"
  user: "root"
  password: "password"
  database: "automation_db"

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "your_password"
  database: "automationexercise"